import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className='flex flex-1 flex-col overflow-hidden'>{children}</div>;
}
