import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@src/assets/scss/index.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dev Tools',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full'>
      <body className={`flex flex-col min-h-full h-full ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
